run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - errcheck
    - gosec
    - unused
    - typecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

version: "2"

